version: '3'

services:
  # Proxy
  nginx:
    depends_on:
      - wordpress
    image: nginx:1.14.2
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
    restart: always
    networks:
      - wpsite
  # Database
  mysql:
    image: mysql:5.7
    volumes:
        - ./db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=nosenose
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpress
    restart: always
    networks:
      - wpsite
  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:4.6
    ports:
      - '8080:80'
    environment:
        - PMA_HOST=mysql
        - MYSQL_ROOT_PASSWORD=nosenose 
    restart: always
    networks:
      - wpsite
  # Worpress
  wordpress:
    depends_on:
      - mysql
    image: wordpress:4.7.1-php7.0-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_USER=wordpress
    restart: always
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  wordpress: